research:
  content: |
    # VLDB 2026: Call for Contributions - Research Track

    ## Overview

    The Proceedings of the VLDB (PVLDB), established in 2008, is a scholarly journal for short and timely research papers pursuing a strict quality assurance process.
    PVLDB is distinguished by a monthly submission process with rapid reviews.
    PVLDB issues are published regularly throughout the year.
    A paper will appear in PVLDB soon after acceptance, and possibly in advance of the VLDB Conference.
    All papers accepted for Volume 19 by June 15, 2026 will form the Research Track of the VLDB 2026 Conference, together with any rollover papers from Volume 18.
    Papers accepted to Volume 19 after June 15, 2026 will be rolled over to the VLDB 2027 Conference.
    At least one author of each accepted paper must attend the VLDB 2026 Conference.
    PVLDB is the only submission channel for research papers to appear in the VLDB 2026 Conference.
    Please see the [Submission Guidelines](https://www.vldb.org/pvldb/volumes/19/submission) for paper submission instructions.
    The submission process for other VLDB 2026 tracks, such as Demonstrations or Tutorials, is different, and is described in their respective calls for papers.

    For details, please visit the PVLDB website: [www.vldb.org/pvldb/volumes/19/contributions](https://www.vldb.org/pvldb/volumes/19/contributions).
