index:
  content: |
    # VLDB 2026: Overview

    The Very Large Data Bases (VLDB) is a premier annual international forum for data management, scalable data science, and database researchers, vendors, practitioners, application developers, and users.
    The forthcoming VLDB 2026 conference is poised to deliver a comprehensive program, featuring an array of research talks, keynote and invited talks, panels, tutorials, demonstrations, industrial tracks, and workshops.
    It will cover a spectrum of research topics related to all aspects of data management, where systems issues play a significant role, such as data management system technology and information management infrastructures, including their very large scale of experimentation, novel architectures, and demanding applications as well as their underpinning theory.

    Key areas of interest for PVLDB include, but are not limited to, data mining and analytics, data privacy and security, database engines, database performance and manageability, distributed database systems, graph and network data, information integration and data quality, languages, machine learning, ai, and databases, novel database architectures, provenance and workflows, specialized and domain-specific data management, text and semi-structured data, and user interfaces.
    These thematic pillars represent the foundational elements underpinning the technological landscape of the emerging applications of the 21st century.

    The VLDB 2026 conference will take place from Aug 31st to 4th September, 2026 in Boston, MA, USA.

  twitter: VLDBconf

officers:
  - title: General Chairs
    people:
      - name: Angela Bonifati
        affiliation: Lyon 1 University & IUF, France
      - name: Mirek Riedewald
        affiliation: Northeastern University, USA
  - title: Program Committee
    people:
      - name: Yanlei Diao
        affiliation: Ecole Polytechnique, France
      - name: Xiaokui Xiao
        affiliation: National University of Singapore
  - title: Associate Editors
    people:
      - name: Walid G. Aref
        affiliation: Purdue University, USA
      - name: Manos Athanassoulis
        affiliation: Boston University, USA
      - name: Carsten Binnig
        affiliation: Technical University of Darmstadt, Germany
      - name: Spyros Blanas
        affiliation: Ohio State University, USA
      - name: Matthias Boehm
        affiliation: Technical University of Berlin, Germany
      - name: Angela Bonifati
        affiliation: University of Lille, France
      - name: K. Selcuk Candan
        affiliation: Arizona State University, USA
      - name: Lei Cao
        affiliation: University of Arizona, USA
      - name: Raul Castro Fernandez
        affiliation: University of Chicago, USA
      - name: Lei Chen
        affiliation: Hong Kong University of Science and Technology, Hong Kong
      - name: Shimin Chen
        affiliation: Chinese Academy of Sciences, China
      - name: Yi Chen
        affiliation: New Jersey Institute of Technology, USA
      - name: Reynold Cheng
        affiliation: University of Hong Kong, Hong Kong
      - name: Alvin Cheung
        affiliation: University of California, Berkeley, USA
      - name: Sudipto Das
        affiliation: Amazon Web Services, USA
      - name: Niv Dayan
        affiliation: University of Toronto, Canada
      - name: Antonis Deligiannakis
        affiliation: Technical University of Crete, Greece
      - name: Jens Dittrich
        affiliation: Saarland University, Germany
      - name: Xin Luna Dong
        affiliation: Meta, USA
      - name: Karima Echihabi
        affiliation: Mohammed VI Polytechnic University, Morocco
      - name: Alan Fekete
        affiliation: University of Sydney, Australia
      - name: Avrilia Floratou
        affiliation: Microsoft, USA
      - name: Jana Giceva
        affiliation: Technical University of Munich, Germany
      - name: Katja Hose
        affiliation: Technical University of Vienna, Austria
      - name: H. V. Jagadish
        affiliation: University of Michigan, USA
      - name: Panos Kalnis
        affiliation: King Abdullah University of Science and Technology, Saudi Arabia
      - name: Georgia Koutrika
        affiliation: Athena Research Center, Greece
      - name: Eric Lo
        affiliation: Chinese University of Hong Kong, Hong Kong
      - name: Nikos Mamoulis
        affiliation: University of Ioannina, Greece
      - name: Stefan Manegold
        affiliation: CWI, Netherlands
      - name: Ioana Manolescu
        affiliation: Inria and Polytechnic Institute of Paris, France
      - name: Norman May
        affiliation: SAP SE, Germany
      - name: Umar Farooq Minhas
        affiliation: Apple, USA
      - name: Fatemeh Nargesian
        affiliation: University of Rochester, USA
      - name: Beng Chin Ooi
        affiliation: National University of Singapore, Singapore
      - name: Fatma Ozcan
        affiliation: Google, USA
      - name: Tamer Ozsu
        affiliation: University of Waterloo, Canada
      - name: Tilmann Rabl
        affiliation: Hasso Plattner Institute and University of Potsdam, Germany
      - name: Mirek Riedewald
        affiliation: Northeastern University, USA
      - name: Jennie Rogers
        affiliation: Northwestern University, USA
      - name: Alkis Simitsis
        affiliation: Athena Research Center, Greece
      - name: Letizia Tanca
        affiliation: Polytechnic University of Milan, Italy
      - name: Nan Tang
        affiliation: Hong Kong University of Science and Technology (GZ), China
      - name: Yuanyuan Tian
        affiliation: Microsoft, USA
      - name: Yongxin Tong
        affiliation: Beihang University, China
      - name: Pinar Tozun
        affiliation: IT University of Copenhagen, Denmark
      - name: Yannis Velegrakis
        affiliation: Utrecht University, Netherlands
      - name: Matthias Weidlich
        affiliation: Humboldt University of Berlin, Germany
      - name: Steven E. Whang
        affiliation: Korea Advanced Institute of Science and Technology, South Korea
      - name: Raymond Chi-Wing Wong
        affiliation: Hong Kong University of Science and Technology, Hong Kong
  - title: Local Chair
    people:
      - name: Manos Athanassoulis
        affiliation: Boston University, USA
  - title: Web Chair
    people:
      - name: Dmytro Bogatov
        affiliation: Amazon Web Services, USA
