opportunities:
  contacts:
    - name: Anand Deshpande
      affiliation: Persistent
    - name: Sharad Mehrotra
      affiliation: UC Irvine
    - name: Ibrahim Sabek
      affiliation: USC
  tiers:
    - name: Diamond
      price: 45000
      color: diamond
      benefits:
        - Acknowledgement in press releases
        - Company logo on banners at registration area
        - Company logo on conference poster
        - Recognition in opening and closing sessions
        - 10 complimentary conference plus workshop registrations
        - Full-page advertisement in conference brochure
        - Linked company logo on website
        - Acknowledgement at conference banquet
        - Executive place in Exhibition Area
        - Pamphlet distribution in conference bag
        - Sponsor talk in conference program
        - Opportunity to submit industrial workshop proposals
    - name: Platinum
      price: 30000
      color: platinum
      benefits:
        - Acknowledgement in press releases
        - Company logo on banners at registration area
        - Company logo on conference poster
        - Recognition in opening and closing sessions
        - 6 complimentary conference plus workshop registrations
        - Full-page advertisement in conference brochure
        - Linked company logo on website
        - Acknowledgement at conference banquet
        - Executive place in Exhibition Area
        - Pamphlet distribution in conference bag
        - Sponsor talk in conference program
    - name: Gold
      price: 15000
      color: gold
      benefits:
        - Company logo on banners at registration area
        - Company logo on conference poster
        - 3 complimentary conference plus workshop registrations
        - Full-page advertisement in conference brochure
        - Linked company logo on website
        - Acknowledgement at conference banquet
        - A place in Exhibition Area
        - Sponsor talk in conference program
    - name: Silver
      price: 10000
      color: silver
      benefits:
        - Company logo on banners at registration area
        - Company logo on conference poster
        - 2 complimentary conference plus workshop registrations
        - Half-page advertisement in conference brochure
        - Linked company logo on website
        - Acknowledgement at conference banquet
        - A place in Exhibition Area
    - name: Bronze
      price: 5000
      color: bronze
      benefits:
        - Company logo on banners at registration area
        - Company logo on conference poster
        - 1 complimentary conference plus workshop registration
        - Half-page advertisement in conference brochure
        - Linked company logo on website
        - Acknowledgement at conference banquet
    - name: Exhibitor/Publisher
      price: 2000
      color: exhibitor
      benefits:
        - Company logo on banners at registration area
        - Company logo on conference poster
        - Half-page advertisement in conference brochure
        - Linked company logo on website
        - A place in Exhibition Area

sponsors:
  levels:
    - name: Diamond
      size: diamond
      companies:
        - name: Amazon
          logo: Diamond/Amazon_Logo_Master_RGB_Squid_Ink+Smile_Orange_MAST (3).svg
    - name: Platinum
      size: platinum
      companies:
        - name: Google
          logo: Platinum/GoogleLogo_RGB_Color.png
        - name: InterSystems
          logo: Platinum/INTS_CreativeDataTechnology_Logo_RGB.jpg
        - name: Jane Street
          logo: Platinum/Jane Street.png
        - name: Oracle
          logo: Platinum/Oracle_rgb_c74634.png
        - name: Snowflake
          logo: Platinum/snowflake-logo-color-rgb@2x.png
    - name: Gold
      size: gold
      companies:
        - name: Databricks
          logo: Gold/Databrics.svg
        - name: eBay
          logo: Gold/Heritage+WHT_ebay_logo_cmyk.jpg
        - name: Megagon Labs
          logo: Gold/MEGAGON LABS.png
        - name: SAP
          logo: Gold/SAP_R_grad_sign.png
    - name: Silver
      size: silver
      companies:
        - name: Spiral
          logo: Silver/Spiral.svg
    - name: Bronze
      size: bronze
      companies:
        - name: Cockroach Labs
          logo: Bronze/CockroachLabs_Full-Logo-Horizontal_Reduced-Color-Light-BG.png
    - name: Exhibitor/Publisher
      size: exhibitor
      companies:
        - name: PuppyGraph
          logo: Exhibitor-Publisher/PuppyGraph_Vertical_Purple__1__9.png
        - name: Weaviate
          logo: Exhibitor-Publisher/weaviate.svg
