tutorials:
  - title: 'Hardware Acceleration for Spatial Databases: Building Next-Generation Query Engines Using Ray Tracing Cores'
    authors: 'Rubao Lee; Liang Geng; Xiaodong Zhang'
  - title: 'Bridging LLMs and Database Systems: A Deep Dive into Enhanced Relational Operators'
    authors: 'Tianjing Zeng; Yin Lin; Rong Zhu; Yunxiang Su; Zhongjun Ding; Bolin Ding; Jingren Zhou'
  - title: 'Are We There Yet? A Grand Tour of ETA Queries'
    authors: 'Areeg Mostafa; Mohamed Hemdan; Mohamed Mokbel'
  - title: 'From Human-Graph to Agent-Graph Interaction: State of the Art and Future Directions'
    authors: 'Sourav S Bhowmick; Byron Choi; Arijit Khan'
  - title: 'Instance-Optimal Acyclic Joins: From Theory to Systems'
    authors: 'Paraschos Koutris; Stijn Vansummeren; Qichen Wang; Yisu Remy Wang; Xiangyao Yu'
  - title: 'Data Management for Agentic Memory: Foundations, Systems, and Challenges'
    authors: 'Guoliang Li; Jiaqi Tian; Xuanhe Zhou'
  - title: 'Advances of Query Processing in Vector Databases'
    authors: 'Jiadong Xie; Yingfan Liu; Jeffrey Xu Yu'
  - title: 'Graph-Based Retrieval-Augmented Generation: Applications, Challenges, Solutions, and Opportunities'
    authors: 'Angela Bonifati; Yixiang Fang; Sibo Wang; Yingli Zhou'
  - title: 'How Can Quantum Computing and Databases Meet "in Practice"? From Algorithms to Systems'
    authors: 'Hanwen Liu; Yiran Li; Ibrahim Sabek; Xuanhe Zhou; Hans-Arno Jacobsen'
  - title: 'Interoperability in Healthcare: A Primer and New Frontiers'
    authors: 'Andra Ionescu; Paris Carbone; Sebastiaan Meijer; Christos Koutras; Juliana Freire; Katja Hose; Jayanth Raghothama'
  - title: 'Graph Foundation Models: State of the Art and Future Directions'
    authors: 'Alexander Zhou; Haoyang Li; Lei Chen'
  - title: 'CRDTs and Databases: A Hands-On Tutorial'
    authors: 'Paulo Sérgio Almeida; Nuno Faria; José Pereira'
  - title: 'Private LLM Inference with Homomorphic Encryption'
    authors: 'Lawrence Lim; Divyakant Agrawal; Amr El Abbadi'
  - title: 'An Extended Tutorial and Vocabulary for Relational Language Design in an Era of AI-Assisted Query Generation'
    authors: 'Wolfgang Gatterbauer'
  - title: 'From Big Time Series Forecasting to Foundation Models for Structured Data'
    authors: 'Xiyuan Zhang; Abdul Fatir Ansari; Christos Faloutsos; George Karypis; Yuyang Wang'
